find_program(_git git)
set(_revision "unknown")
if (_git)
    execute_process(COMMAND "${_git}" rev-parse --short=8 HEAD
        WORKING_DIRECTORY "${SOURCE_DIR}" OUTPUT_VARIABLE _commit
        OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_QUIET RESULT_VARIABLE _result)
    if (_result EQUAL 0 AND _commit MATCHES "^[0-9a-f]+$")
        set(_revision "${_commit}")
        execute_process(COMMAND "${_git}" status --porcelain --untracked-files=normal
            WORKING_DIRECTORY "${SOURCE_DIR}" OUTPUT_VARIABLE _status
            ERROR_QUIET RESULT_VARIABLE _status_result)
        if (NOT _status_result EQUAL 0)
            string(APPEND _revision "-unknown-state")
        elseif (NOT _status STREQUAL "")
            string(APPEND _revision "-dirty")
        endif()
    endif()
endif()
file(MAKE_DIRECTORY "${OUTPUT_DIR}")
function(write_if_changed name content)
    set(_previous "")
    if (EXISTS "${OUTPUT_DIR}/${name}")
        file(READ "${OUTPUT_DIR}/${name}" _previous)
    endif()
    if (NOT _previous STREQUAL content)
        file(WRITE "${OUTPUT_DIR}/${name}" "${content}")
    endif()
endfunction()
write_if_changed(engine_sim_build.h "#pragma once\n#define ENGINE_SIM_BUILD_REVISION \"${_revision}\"\n")
write_if_changed(build-info.txt "Engine Sim build revision: ${_revision}\nA dirty suffix means the build included local working-tree changes.\n")
