# The pinned Delta Studio revision passes sample counts to DirectSound's byte
# count parameters in its segmented unlock. Patch a build-directory copy rather
# than modifying the submodule checkout or depending on an unpublished commit.
if (NOT WIN32)
    return()
endif()
get_target_property(_delta_dir delta-core SOURCE_DIR)
get_target_property(_delta_sources delta-core SOURCES)
set(_audio_source "${_delta_dir}/src/yds_ds8_audio_source.cpp")
file(READ "${_audio_source}" _audio_code)
set(_old_unlock "m_buffer->Unlock(segment1, segment1Size, segment2, segment2Size)")
set(_new_unlock "m_buffer->Unlock(segment1, m_audioParameters.GetSizeFromSamples(segment1Size), segment2, m_audioParameters.GetSizeFromSamples(segment2Size))")
string(FIND "${_audio_code}" "${_old_unlock}" _match)
if (_match EQUAL -1)
    message(FATAL_ERROR "Delta audio source changed; review or remove cmake/DeltaAudioFix.cmake")
endif()
string(REPLACE "${_old_unlock}" "${_new_unlock}" _audio_code "${_audio_code}")
# Preserve the original source's header lookup when compiling its generated copy.
string(REPLACE "\"../include/" "\"${_delta_dir}/include/" _audio_code "${_audio_code}")
set(_patched_source "${PROJECT_BINARY_DIR}/dependency-fixes/yds_ds8_audio_source.cpp")
file(MAKE_DIRECTORY "${PROJECT_BINARY_DIR}/dependency-fixes")
set(_previous_code "")
if (EXISTS "${_patched_source}")
    file(READ "${_patched_source}" _previous_code)
endif()
if (NOT _previous_code STREQUAL _audio_code)
    file(WRITE "${_patched_source}" "${_audio_code}")
endif()
set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${_audio_source}")
set(_found_source FALSE)
foreach(_source IN LISTS _delta_sources)
    if (_source STREQUAL "src/yds_ds8_audio_source.cpp" OR _source STREQUAL "${_audio_source}")
        list(REMOVE_ITEM _delta_sources "${_source}")
        set(_found_source TRUE)
    endif()
endforeach()
if (NOT _found_source)
    message(FATAL_ERROR "Delta audio target changed; review cmake/DeltaAudioFix.cmake")
endif()
set_property(TARGET delta-core PROPERTY SOURCES "${_delta_sources}")
target_sources(delta-core PRIVATE "${_patched_source}")
