# Reset the pinned video queue between recordings without changing its submodule.
get_target_property(_video_dir direct-to-video SOURCE_DIR)
get_target_property(_video_sources direct-to-video SOURCES)
set(_queue_source "${_video_dir}/src/frame_queue.cpp")
file(READ "${_queue_source}" _queue_code)
set(_old_init "m_frames = new Frame[m_capacity];")
string(FIND "${_queue_code}" "${_old_init}" _match)
if (_match EQUAL -1)
    message(FATAL_ERROR "Video queue changed; review cmake/VideoCaptureFix.cmake")
endif()
string(REPLACE "${_old_init}" "m_stopped = false;\n    ${_old_init}" _queue_code "${_queue_code}")
string(REPLACE "\"../include/" "\"${_video_dir}/include/" _queue_code "${_queue_code}")
set(_patched_queue "${PROJECT_BINARY_DIR}/dependency-fixes/frame_queue.cpp")
file(MAKE_DIRECTORY "${PROJECT_BINARY_DIR}/dependency-fixes")
set(_previous_queue "")
if (EXISTS "${_patched_queue}")
    file(READ "${_patched_queue}" _previous_queue)
endif()
if (NOT _previous_queue STREQUAL _queue_code)
    file(WRITE "${_patched_queue}" "${_queue_code}")
endif()
set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${_queue_source}")
set(_found_queue FALSE)
foreach(_source IN LISTS _video_sources)
    if (_source STREQUAL "src/frame_queue.cpp" OR _source STREQUAL "${_queue_source}")
        list(REMOVE_ITEM _video_sources "${_source}")
        set(_found_queue TRUE)
    endif()
endforeach()
if (NOT _found_queue)
    message(FATAL_ERROR "Video target changed; review cmake/VideoCaptureFix.cmake")
endif()
set_property(TARGET direct-to-video PROPERTY SOURCES "${_video_sources}")
target_sources(direct-to-video PRIVATE "${_patched_queue}")

# Current FFmpeg returns immutable codec and output-format descriptors.
set(_encoder_source "${_video_dir}/src/encoder.cpp")
file(READ "${_encoder_source}" _encoder_code)
foreach(_declaration "AVCodec **codec" "AVCodec *videoCodec" "AVOutputFormat *fmt")
    string(FIND "${_encoder_code}" "${_declaration}" _match)
    if (_match EQUAL -1)
        message(FATAL_ERROR "Video encoder changed; review cmake/VideoCaptureFix.cmake")
    endif()
    string(REPLACE "${_declaration}" "const ${_declaration}" _encoder_code "${_encoder_code}")
endforeach()
set(_packed_copy [=[    memcpy(
        target->data[0],
        src->m_rgb,
        (size_t)src->m_width * src->m_height * pixelSize);]=])
set(_strided_copy [=[    const size_t rowBytes = (size_t)src->m_width * pixelSize;
    for (int y = 0; y < src->m_height; ++y) {
        memcpy(target->data[0] + (size_t)y * target->linesize[0],
            src->m_rgb + (size_t)y * rowBytes, rowBytes);
    }]=])
string(FIND "${_encoder_code}" "${_packed_copy}" _match)
if (_match EQUAL -1)
    message(FATAL_ERROR "Video frame copy changed; review cmake/VideoCaptureFix.cmake")
endif()
string(REPLACE "${_packed_copy}" "${_strided_copy}" _encoder_code "${_encoder_code}")
set(_unchecked_frame "            generateFrame(frame, videoStream.frame, m_videoSettings, &videoStream);")
set(_writable_frame [=[            // The codec may still hold a reference to the previous frame's pixels.
            if (av_frame_make_writable(videoStream.frame) < 0) {
                err = Error::CouldNotAllocateFrame;
                goto end;
            }
            generateFrame(frame, videoStream.frame, m_videoSettings, &videoStream);]=])
string(FIND "${_encoder_code}" "${_unchecked_frame}" _match)
if (_match EQUAL -1)
    message(FATAL_ERROR "Video frame conversion changed; review cmake/VideoCaptureFix.cmake")
endif()
string(REPLACE "${_unchecked_frame}" "${_writable_frame}" _encoder_code "${_encoder_code}")
set(_old_trailer "    av_write_trailer(oc);")
set(_flushed_trailer [=[    // Drain delayed packets before finalizing the container.
    err = writeFrame(oc, videoStream.codecContext, videoStream.av_stream,
        nullptr, videoStream.tempPacket);
    if (err != Error::None) goto end;
    if (av_write_trailer(oc) < 0) err = Error::CouldNotWriteOutputPacket;]=])
string(FIND "${_encoder_code}" "${_old_trailer}" _match)
if (_match EQUAL -1)
    message(FATAL_ERROR "Video trailer changed; review cmake/VideoCaptureFix.cmake")
endif()
string(REPLACE "${_old_trailer}" "${_flushed_trailer}" _encoder_code "${_encoder_code}")
set(_unchecked_close "        avio_closep(&oc->pb);")
set(_checked_close [=[        if (avio_closep(&oc->pb) < 0 && m_error == Error::None)
            m_error = Error::CouldNotWriteOutputPacket;]=])
string(FIND "${_encoder_code}" "${_unchecked_close}" _match)
if (_match EQUAL -1)
    message(FATAL_ERROR "Video file cleanup changed; review cmake/VideoCaptureFix.cmake")
endif()
# Cleanup runs under m_lock after publishing err; retain any earlier failure.
string(REPLACE "${_unchecked_close}" "${_checked_close}" _encoder_code "${_encoder_code}")
set(_unchecked_stream "        addStream(&videoStream, oc, &videoCodec, fmt->video_codec, m_videoSettings);")
set(_checked_stream [=[        err = addStream(&videoStream, oc, &videoCodec, fmt->video_codec, m_videoSettings);
        if (err != Error::None) goto end;]=])
string(FIND "${_encoder_code}" "${_unchecked_stream}" _match)
if (_match EQUAL -1)
    message(FATAL_ERROR "Video stream setup changed; review cmake/VideoCaptureFix.cmake")
endif()
string(REPLACE "${_unchecked_stream}" "${_checked_stream}" _encoder_code "${_encoder_code}")
string(REPLACE "\"../include/" "\"${_video_dir}/include/" _encoder_code "${_encoder_code}")
set(_patched_encoder "${PROJECT_BINARY_DIR}/dependency-fixes/encoder.cpp")
set(_previous_encoder "")
if (EXISTS "${_patched_encoder}")
    file(READ "${_patched_encoder}" _previous_encoder)
endif()
if (NOT _previous_encoder STREQUAL _encoder_code)
    file(WRITE "${_patched_encoder}" "${_encoder_code}")
endif()
set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${_encoder_source}")
get_target_property(_video_sources direct-to-video SOURCES)
set(_found_encoder FALSE)
foreach(_source IN LISTS _video_sources)
    if (_source STREQUAL "src/encoder.cpp" OR _source STREQUAL "${_encoder_source}")
        list(REMOVE_ITEM _video_sources "${_source}")
        set(_found_encoder TRUE)
    endif()
endforeach()
if (NOT _found_encoder)
    message(FATAL_ERROR "Video encoder target changed; review cmake/VideoCaptureFix.cmake")
endif()
set_property(TARGET direct-to-video PROPERTY SOURCES "${_video_sources}")
target_sources(direct-to-video PRIVATE "${_patched_encoder}")
