# Reset the pinned video queue between recordings without changing its submodule.
get_target_property(_video_dir direct-to-video SOURCE_DIR)
get_target_property(_video_sources direct-to-video SOURCES)
set(_queue_source "${_video_dir}/src/frame_queue.cpp")
file(READ "${_queue_source}" _queue_code)
set(_old_init "m_frames = new Frame[m_capacity];")
string(FIND "${_queue_code}" "${_old_init}" _match)
if (_match EQUAL -1)
    message(FATAL_ERROR "Video queue changed; review cmake/VideoCaptureFix.cmake")
endif()
string(REPLACE "${_old_init}" "m_stopped = false;\n    ${_old_init}" _queue_code "${_queue_code}")
string(REPLACE "\"../include/" "\"${_video_dir}/include/" _queue_code "${_queue_code}")
set(_patched_queue "${PROJECT_BINARY_DIR}/dependency-fixes/frame_queue.cpp")
file(MAKE_DIRECTORY "${PROJECT_BINARY_DIR}/dependency-fixes")
set(_previous_queue "")
if (EXISTS "${_patched_queue}")
    file(READ "${_patched_queue}" _previous_queue)
endif()
if (NOT _previous_queue STREQUAL _queue_code)
    file(WRITE "${_patched_queue}" "${_queue_code}")
endif()
set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${_queue_source}")
set(_found_queue FALSE)
foreach(_source IN LISTS _video_sources)
    if (_source STREQUAL "src/frame_queue.cpp" OR _source STREQUAL "${_queue_source}")
        list(REMOVE_ITEM _video_sources "${_source}")
        set(_found_queue TRUE)
    endif()
endforeach()
if (NOT _found_queue)
    message(FATAL_ERROR "Video target changed; review cmake/VideoCaptureFix.cmake")
endif()
set_property(TARGET direct-to-video PROPERTY SOURCES "${_video_sources}")
target_sources(direct-to-video PRIVATE "${_patched_queue}")
